import "@radix-ui/themes/styles.css";
import "react-loading-skeleton/dist/skeleton.css";
import "./theme-config.css";
import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import Navbar from "./Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className={`${inter.variable} min-h-full flex flex-col`}>
        <Theme accentColor="purple">
          <Navbar />
          <main className="flex-1 p-5">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
